# Generated by Django 4.1.3 on 2022-12-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='users',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='carts',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productsinorder',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='productsinorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductInCart',
        ),
        migrations.DeleteModel(
            name='ProductsInOrder',
        ),
    ]
